services:
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./wardrobify_react/ui:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
  database:
    image: postgres:14.2-bullseye
    volumes:
      - wardrobify_database:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=wardrobe
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432
  wardrobe-api:
    build:
      context: ./wardrobify/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8200:8000"
    volumes:
      - ./wardrobify/api:/app
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://wardrobe:password@database:5432/wardrobe
      WAIT_HOSTS: database:5432
      WAIT_TIMEOUT: 240
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - /pgadmin/var/lib/pgadmin4
    ports:
      - "8060:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "rbbitphoto@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
volumes:
  wardrobify_database:
    external: true