# Generated by Django 4.0.3 on 2022-11-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('closet_number', models.SmallIntegerField()),
                ('closet_size', models.SmallIntegerField()),
            ],
        ),
    ]
