# Generated by Django 4.0.3 on 2022-10-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothing', '0002_alter_footwear_top_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('closet_number', models.SmallIntegerField()),
                ('closet_size', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Outfits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_name', models.CharField(max_length=120)),
                ('accessories', models.ManyToManyField(to='clothing.accessorie')),
                ('bottom', models.ManyToManyField(to='clothing.bottom')),
                ('footwear', models.ManyToManyField(to='clothing.footwear')),
                ('top', models.ManyToManyField(to='clothing.top')),
                ('undergarment', models.ManyToManyField(to='clothing.undergarment')),
            ],
        ),
    ]
