# Generated by Django 4.0.3 on 2022-10-10 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('closet_number', models.SmallIntegerField()),
                ('closet_size', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_name', models.CharField(max_length=120)),
                ('accessories', models.ManyToManyField(to='clothing.accessorie')),
                ('bottom', models.ManyToManyField(to='clothing.bottom')),
                ('closet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit', to='closets.closet')),
                ('footwear', models.ManyToManyField(to='clothing.footwear')),
                ('top', models.ManyToManyField(to='clothing.top')),
                ('undergarment', models.ManyToManyField(to='clothing.undergarment')),
            ],
        ),
    ]
