# Generated by Django 4.0.3 on 2022-11-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
        ('closets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='accessories',
            field=models.ManyToManyField(blank=True, to='clothing.accessorie'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='bottom',
            field=models.ManyToManyField(blank=True, to='clothing.bottom'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='footwear',
            field=models.ManyToManyField(blank=True, to='clothing.footwear'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='top',
            field=models.ManyToManyField(blank=True, to='clothing.top'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='undergarment',
            field=models.ManyToManyField(blank=True, to='clothing.undergarment'),
        ),
    ]
