# Generated by Django 4.0.3 on 2022-10-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_alter_footwear_top_type'),
        ('closets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Closets',
            new_name='Closet',
        ),
        migrations.RenameModel(
            old_name='Outfits',
            new_name='Outfit',
        ),
    ]
