# Generated by Django 4.0.3 on 2022-10-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('brand', models.CharField(max_length=32)),
                ('accessory_type', models.CharField(choices=[('HEAD', 'Headwear'), ('WTCH', 'Watches'), ('BRCLT', 'Bracelets'), ('SCRF', 'Scarves'), ('NECK', 'Neckwear'), ('GLVE', 'Gloves'), ('BELT', 'Belts')], default='HEAD', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Bottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('brand', models.CharField(max_length=32)),
                ('top_type', models.CharField(choices=[('PNTS', 'Pants'), ('SHRT', 'Shorts'), ('SKRT', 'Skirts'), ('CRPI', 'Capris'), ('JOG', 'Joggers'), ('BIKE', 'Bike Shorts'), ('SKORT', 'Skorts'), ('LEGG', 'Leggings')], default='PNTS', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('brand', models.CharField(max_length=32)),
                ('top_type', models.CharField(choices=[('SHOE', 'Shoes'), ('HEEL', 'Heels'), ('SAND', 'Sandals'), ('SLDE', 'Slides'), ('SOCK', 'Socks'), ('BOOT', 'Boots')], default='SHOE', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('brand', models.CharField(max_length=32)),
                ('top_type', models.CharField(choices=[('TEE', 'T-Shirts'), ('JCKT', 'Jackets'), ('SWTR', 'Sweaters'), ('CARD', 'Cardigans'), ('HOOD', 'Hoodies'), ('VST', 'Vests'), ('DRES', 'Dresses'), ('CVRA', 'Coveralls')], default='TEE', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Undergarment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('brand', models.CharField(max_length=32)),
                ('top_type', models.CharField(choices=[('UNSHRT', 'Undershirts'), ('BRA', 'Bras'), ('BKNIT', 'Bikini Top'), ('BKNIB', 'Bikini Bottom'), ('UNWR', 'Underwear'), ('SPTBR', 'Sports Bra'), ('LNGR', 'Lingerie')], default='UNSHRT', max_length=15)),
            ],
        ),
    ]
