# Generated by Django 4.0.3 on 2022-11-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_Category',
            new_name='ItemCategory',
        ),
        migrations.RenameModel(
            old_name='Outfit_Item',
            new_name='OutfitItem',
        ),
    ]
