# Generated by Django 4.0.3 on 2022-10-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footwear',
            name='top_type',
            field=models.CharField(choices=[('SHOE', 'Shoes'), ('HEEL', 'Heels'), ('SAND', 'Sandals'), ('SLDE', 'Slides'), ('SOCK', 'Socks'), ('BOOT', 'Boots')], default='SHOE', max_length=12),
        ),
    ]
